//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ADSDBEntities : DbContext
    {
        public ADSDBEntities()
            : base("name=ADSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ad> Ad { get; set; }
        public virtual DbSet<AdClient> AdClient { get; set; }
        public virtual DbSet<AdPack> AdPack { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientCustomer> ClientCustomer { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Pack> Pack { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<AdTopic> AdTopic { get; set; }
        public virtual DbSet<ClientTopic> ClientTopic { get; set; }
        public virtual DbSet<Constraint> Constraint { get; set; }
        public virtual DbSet<Topic> Topic { get; set; }
    }
}
