//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdUser
    {
        public int Id { get; set; }
        public int AdID { get; set; }
        public int UserID { get; set; }
        public int Views { get; set; }
    
        public virtual Ad Ad { get; set; }
        public virtual User User { get; set; }
    }
}
